# Generated by Django 2.2.5 on 2020-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '成绩',
            },
        ),
        migrations.CreateModel(
            name='TechFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '教学课件',
            },
        ),
        migrations.CreateModel(
            name='TechWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': '教学作业',
            },
        ),
    ]
