# Generated by Django 2.2.5 on 2020-05-16 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
        ('tech_assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techwork',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.CourseVideo'),
        ),
        migrations.AddField(
            model_name='techwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techfile',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.CourseVideo'),
        ),
        migrations.AddField(
            model_name='coursegrate',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_assist.TechFile'),
        ),
    ]
